### PR TITLE
Only build docker for linux #17

### PR DESCRIPTION
**Pull request by BreakingPitt**
Fixes: Removes Docker ARM platform builds from CI as requested in #17

### CODE REVIEW

**Comment by peterdudfield** [comment]
Thanks @BreakingPitt for jumping on this

**Comment by BreakingPitt** [comment]
@peterdudfield Seems that the Integration Test in the check were not successful but they are not related to the change that I have done, how can I fix/work/avoid these errors?

**Comment by peterdudfield** [comment]
> @peterdudfield Seems that the Integration Test in the check were not successful but they are not related to the change that I have done, how can I fix/work/avoid these errors?

Yea, this is nothing you did - might be something to do with you be an `outside contributor` so that CI might not have access to those secrets

**Comment by peterdudfield** [comment]
if you fancy looking at #15 that would be great too? No pressure though

**Review by peterdudfield — APPROVED** [review]

**Comment by BreakingPitt** [comment]
@peterdudfield  Sure... Would you be so kind as to provide a little more context in the issue, to see if I can tackle the task?

**Comment by peterdudfield** [comment]
> @peterdudfield Sure... Would you be so kind as to provide a little more context in the issue, to see if I can tackle the task?

Ill add it to the issue

**Review by devsjc — APPROVED** [review]

**Comment by devsjc** [comment]
You're right, the integration test failing is a permissions issue and nothing to do with your change! I'll sort that soon and merge this anyway.

**Comment by BreakingPitt** [comment]
Thanks @peterdudfield @devsjc

**Pull request merged**
